version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - ${PG_PATH}:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_DB_USER}
      POSTGRES_PASSWORD: ${PG_DB_PW}
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${PG_DB_USER}:${PG_DB_PW}@db:5432/${PG_DB}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BUILD_MODE: ${BUILD_MODE}
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  postgres_data:
