# Generated by Django 5.0.1 on 2024-03-02 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluator', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_tutor', to='user.tutor'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluator.course'),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='assignments',
            field=models.ManyToManyField(through='evaluator.AssignmentInstance', to='evaluator.assignment'),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluator.course'),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='course_leaders',
            field=models.ManyToManyField(related_name='ci_course_leaders', to='user.courseleader'),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='tutors',
            field=models.ManyToManyField(related_name='ci_tutors', to='user.tutor'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='course_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluator.courseinstance'),
        ),
        migrations.AddField(
            model_name='assignmentinstance',
            name='course_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_instances', to='evaluator.courseinstance'),
        ),
        migrations.AddField(
            model_name='degreeprogram',
            name='dp_director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.degreeprogramdirector'),
        ),
        migrations.AddField(
            model_name='course',
            name='degree_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluator.degreeprogram'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='degree_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluator.degreeprogram'),
        ),
        migrations.AddField(
            model_name='previousdeduction',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluator.assignment'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluator.classgroup'),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='students',
            field=models.ManyToManyField(through='evaluator.CourseEnrollment', to='evaluator.student'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluator.student'),
        ),
        migrations.AddField(
            model_name='correction',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_student', to='evaluator.student'),
        ),
        migrations.AddField(
            model_name='tutorassignment',
            name='assignment_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_assignments', to='evaluator.assignmentinstance'),
        ),
        migrations.AddField(
            model_name='tutorassignment',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_assignments', to='user.tutor'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('nr', 'course'), name='assignment_pk'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentinstance',
            unique_together={('assignment', 'course_instance')},
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('name', 'degree_program'), name='course_pk'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(('file_name__contains', '{lastname}'), ('file_name__contains', '{nr}')), name='Course.filename Check'),
        ),
        migrations.AddConstraint(
            model_name='courseinstance',
            constraint=models.UniqueConstraint(fields=('year', 'course'), name='course_instance_pk'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course_instance'), name='course_enrollment_pk'),
        ),
        migrations.AlterUniqueTogether(
            name='tutorassignment',
            unique_together={('tutor', 'assignment_instance')},
        ),
    ]
