# Generated by Django 5.0.7 on 2024-07-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0003_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='status',
            new_name='type',
        ),
    ]
